apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    function: kafka-source
  name: kafka-source
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      function: kafka-source
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        function: kafka-source
      name: kafka-source
    spec:
      containers:
      - image: dturanski/kafka-source:0.0.1
        imagePullPolicy: IfNotPresent
        name: main
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --inputs
        - kafka-source
        - --outputs
        - events
        - --group
        - kafka-source
        - --protocol
        - grpc
        - --brokers
        - projectriff-kafka.riff-system:9092
        image: projectriff/function-sidecar:0.0.6-snapshot
        imagePullPolicy: IfNotPresent
        name: sidecar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

