== Kafka Source

This is a WIP exploring how to create a riff event-source connected to an external Kafka broker

NOTE: Tested on Docker for Mac (edge channel) with Kubernetes enabled

== Install riff:

```
$ helm install projectriff/riff --name projectriff --devel --namespace riff-system --set kafka.create=true --set rbac.create=false --set httpGateway.service.type=NodePort
```

== Install a separate Kafka broker using the riff helm chart for kafka:

```
$ helm install projectriff/kafka --name external
```

Get the external kafka host IP:

```
docker ps -f name=k8s_kafka_external-kafka* -q | xargs docker inspect | grep ADVERTISED
```

== Using minio to produce messages

Install the https://minio.io/downloads.html#download-client[minio client]

```
$ create local mount directories, e.g., `/mnt/data` and `/mnt/config`
$ docker run --rm -p 9000:9000 --name minio1 -v /mnt/data:/data -v /mnt/config:/root/.minio  minio/minio:latest server /data
```

The initial run will create credentials a `config.json` in `/mnt/config`.  It will also display a message like:

```
mc config host add myminio http://172.17.0.2:9000 6225PS5P2A3OVKPA6H0J W9TdOPYjeAEmdxLlK88BExK0u8FqxxDUi1YleWaw
```

Edit `/mnt/data/config.json` to enable Kafka notifications. Edit generated "kafka" entry, using the kafka host IP.

```
"kafka": {
			"1": {
				"enable": true,
				"brokers": [
					"<kafka-ip>:9092"
				],
				"topic": "bucketevents"
			}
		},
```

Restart the minio docker container.  You should see this message:

```
SQS ARNs:  arn:minio:sqs::1:kafka
```

Create a bucket and create and register an event for that bucket.

```
$ mc mb myminio/foobar
Bucket created successfully `myminio/foobar`.

$mc events add myminio/foobar arn:minio:sqs::1:kafka
Successfully added arn:minio:sqs::1:kafka

$ mc events list myminio/foobar
arn:minio:sqs::1:kafka   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter:
```

The subscription is for any object event in the bucket. Generate messages to the `bucketevents` topic:

```
$ mc cp pom.xml myminio/foobar
```

== Build and deploy function

```
$ ./mvnw clean package
$ riff build
$ riff apply
```

== Scale to one instance and test

```
$ kubectl scale deployment kafka-source --replicas=1
```

Then copy something to the bucket

```
$ mc cp pom.xml myminio/foobar
```

You can use the riff provided `topics` command to tail the events

```
$ topics tail -n events
```
